/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as CyberHygieneRouteImport } from './routes/cyber-hygiene'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonIdRouteImport } from './routes/lesson.$id'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicHooksSeoScanRouteImport } from './routes/api/public/hooks/seo-scan'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const CyberHygieneRoute = CyberHygieneRouteImport.update({
  id: '/cyber-hygiene',
  path: '/cyber-hygiene',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonIdRoute = LessonIdRouteImport.update({
  id: '/lesson/$id',
  path: '/lesson/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksSeoScanRoute = ApiPublicHooksSeoScanRouteImport.update({
  id: '/api/public/hooks/seo-scan',
  path: '/api/public/hooks/seo-scan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/badges': typeof BadgesRoute
  '/cyber-hygiene': typeof CyberHygieneRoute
  '/delete-account': typeof DeleteAccountRoute
  '/lessons': typeof LessonsRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/lesson/$id': typeof LessonIdRoute
  '/api/public/hooks/seo-scan': typeof ApiPublicHooksSeoScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/badges': typeof BadgesRoute
  '/cyber-hygiene': typeof CyberHygieneRoute
  '/delete-account': typeof DeleteAccountRoute
  '/lessons': typeof LessonsRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/lesson/$id': typeof LessonIdRoute
  '/api/public/hooks/seo-scan': typeof ApiPublicHooksSeoScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/badges': typeof BadgesRoute
  '/cyber-hygiene': typeof CyberHygieneRoute
  '/delete-account': typeof DeleteAccountRoute
  '/lessons': typeof LessonsRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/lesson/$id': typeof LessonIdRoute
  '/api/public/hooks/seo-scan': typeof ApiPublicHooksSeoScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/auth'
    | '/badges'
    | '/cyber-hygiene'
    | '/delete-account'
    | '/lessons'
    | '/privacy'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/insights'
    | '/settings'
    | '/lesson/$id'
    | '/api/public/hooks/seo-scan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/auth'
    | '/badges'
    | '/cyber-hygiene'
    | '/delete-account'
    | '/lessons'
    | '/privacy'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/insights'
    | '/settings'
    | '/lesson/$id'
    | '/api/public/hooks/seo-scan'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accessibility'
    | '/auth'
    | '/badges'
    | '/cyber-hygiene'
    | '/delete-account'
    | '/lessons'
    | '/privacy'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/insights'
    | '/_authenticated/settings'
    | '/lesson/$id'
    | '/api/public/hooks/seo-scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccessibilityRoute: typeof AccessibilityRoute
  AuthRoute: typeof AuthRoute
  BadgesRoute: typeof BadgesRoute
  CyberHygieneRoute: typeof CyberHygieneRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  LessonsRoute: typeof LessonsRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  LessonIdRoute: typeof LessonIdRoute
  ApiPublicHooksSeoScanRoute: typeof ApiPublicHooksSeoScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyber-hygiene': {
      id: '/cyber-hygiene'
      path: '/cyber-hygiene'
      fullPath: '/cyber-hygiene'
      preLoaderRoute: typeof CyberHygieneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$id': {
      id: '/lesson/$id'
      path: '/lesson/$id'
      fullPath: '/lesson/$id'
      preLoaderRoute: typeof LessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/seo-scan': {
      id: '/api/public/hooks/seo-scan'
      path: '/api/public/hooks/seo-scan'
      fullPath: '/api/public/hooks/seo-scan'
      preLoaderRoute: typeof ApiPublicHooksSeoScanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccessibilityRoute: AccessibilityRoute,
  AuthRoute: AuthRoute,
  BadgesRoute: BadgesRoute,
  CyberHygieneRoute: CyberHygieneRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  LessonsRoute: LessonsRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  LessonIdRoute: LessonIdRoute,
  ApiPublicHooksSeoScanRoute: ApiPublicHooksSeoScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
